/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 * Example for using IR driver
 */

#include <stdint.h>
#include"IR_Interface.h"

extern uint8_t IR1;
extern uint8_t IR2;



int main(void)
{

	/*Initialize IR driver*/
	IR_Init();

	/* Loop forever */
	while(1)
	{
      /*Values of IR1 & IR2 will be updated*/
	  IR_u8Read_LeftIR();
      IR_u8Read_RightIR();
	}
}
